/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/usuarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista usuários da unidade do administrador */
    get: {
      parameters: {
        query?: {
          busca?: string;
          status?: 'ativo' | 'bloqueado' | 'convidado';
          pagina?: number;
          limite?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              itens: components['schemas']['Usuario'][];
              pagina: number;
              limite: number;
              total: number;
            };
          };
        };
        /** @description Não autenticado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Perfil sem permissão */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    /** Cria usuário (status convidado) e envia o convite por e-mail */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            nome: string;
            email: string;
            /** @enum {string} */
            perfil: 'secretaria' | 'clinica' | 'adm_clinica' | 'laboratorio' | 'adm_laboratorio';
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Usuario'];
          };
        };
        /** @description Dados ou perfil inválidos para a unidade */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Sem permissão ou CSRF inválido */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description E-mail já cadastrado */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/usuarios/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalha um usuário da unidade */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Usuario'];
          };
        };
        /** @description Não encontrado (inclui usuários de outra unidade) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita nome, e-mail ou perfil */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            nome?: string;
            email?: string;
            /** @enum {string} */
            perfil?: 'secretaria' | 'clinica' | 'adm_clinica' | 'laboratorio' | 'adm_laboratorio';
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Usuario'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description E-mail já cadastrado */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/usuarios/{id}/bloquear': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bloqueia o usuário e revoga as sessões abertas */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Usuario'];
          };
        };
        /** @description Tentativa de bloquear a si mesmo */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/usuarios/{id}/desbloquear': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reativa um usuário bloqueado */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Usuario'];
          };
        };
        /** @description Usuário não está bloqueado */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/usuarios/{id}/redefinir-senha': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispara o e-mail de redefinição (ou reenvia o convite) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description E-mail disparado */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/prontuario': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resumo do prontuário — alertas, anamnese atual e linha do tempo (acesso registrado) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Prontuario'];
          };
        };
        /** @description Somente o perfil Clínica (dentista) */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Paciente não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/anamneses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Versões da anamnese (só metadados; acesso registrado) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AnamneseMeta'][];
          };
        };
      };
    };
    put?: never;
    /** Registra NOVA versão da anamnese (nunca sobrescreve — RF-CLI-003) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            respostas: {
              [key: string]: unknown;
            };
            alertas?: components['schemas']['Alerta'][];
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Anamnese'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Usuário não é profissional ativo */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/evolucoes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Evoluções clínicas com adendos (acesso registrado) */
    get: {
      parameters: {
        query?: {
          pagina?: number;
          limite?: number;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              itens: components['schemas']['Evolucao'][];
              pagina: number;
              limite: number;
              total: number;
            };
          };
        };
      };
    };
    put?: never;
    /** Registra evolução (sem edição nem exclusão — RN-006) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            conteudo: string;
            /** Format: uuid */
            consulta_id?: string | null;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              id: string;
              /** Format: date-time */
              criado_em: string;
            };
          };
        };
        /** @description Dados inválidos ou consulta de outro paciente */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/acessos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Quem abriu o prontuário, quando e o quê (Clínica e Adm. Clínica) */
    get: {
      parameters: {
        query?: {
          pagina?: number;
          limite?: number;
        };
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              itens: components['schemas']['Acesso'][];
              pagina: number;
              limite: number;
              total: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/prontuario/pdf': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Link de uso único (60 s) para baixar o prontuário em PDF, gerado no servidor */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LinkDownload'];
          };
        };
        /** @description Paciente não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/anamneses/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Conteúdo de uma versão da anamnese (acesso registrado) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Anamnese'];
          };
        };
        /** @description Não encontrada */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/anamneses/{id}/assinatura': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Assina a anamnese (só o autor, uma única vez) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Anamnese'];
          };
        };
        /** @description Não é o autor */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Já assinada */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/evolucoes/{id}/adendos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Corrige/complementa uma evolução por adendo (RN-006 — o texto original não muda) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            conteudo: string;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** Format: uuid */
              id: string;
              /** Format: date-time */
              criado_em: string;
            };
          };
        };
        /** @description Evolução não encontrada */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/procedimentos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Catálogo de procedimentos (Clínica e Adm. Clínica) */
    get: {
      parameters: {
        query?: {
          busca?: string;
          ativo?: 'true' | 'false' | 'todos';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ItemCatalogo'][];
          };
        };
      };
    };
    put?: never;
    /** Cadastra item do catálogo */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            codigo: string;
            nome: string;
            especialidade?: string | null;
            duracao_min?: number;
            valor_padrao?: number;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ItemCatalogo'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Código já usado */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/procedimentos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita item do catálogo (inclusive ativar/inativar) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            codigo?: string;
            nome?: string;
            especialidade?: string | null;
            duracao_min?: number;
            valor_padrao?: number;
            ativo?: boolean;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ItemCatalogo'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Código já usado */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/pacientes/{id}/procedimentos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Procedimentos do paciente com adendos (acesso registrado) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProcedimentoPaciente'][];
          };
        };
      };
    };
    put?: never;
    /** Registra procedimento por dente (FDI) e faces (V, L, M, D, O, I) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            catalogo_id: string;
            dente?: number | null;
            faces?: ('V' | 'L' | 'M' | 'D' | 'O' | 'I')[];
            /** @enum {string} */
            status?: 'planejado' | 'em_andamento' | 'concluido';
            /** Format: date */
            data?: string | null;
            valor?: number | null;
            observacao?: string | null;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProcedimentoPaciente'];
          };
        };
        /** @description Dente/face inválido ou catálogo inativo */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/odontograma': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Situação por elemento dentário (acesso registrado) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Odontograma'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/procedimentos-paciente/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita procedimento aberto; concluído ou cancelado só aceita adendo (RN-006) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            dente?: number | null;
            faces?: ('V' | 'L' | 'M' | 'D' | 'O' | 'I')[];
            /** @enum {string} */
            status?: 'planejado' | 'em_andamento' | 'concluido' | 'cancelado';
            /** Format: date */
            data?: string | null;
            valor?: number;
            observacao?: string | null;
            adendo?: string;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProcedimentoPaciente'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Transição inválida ou procedimento fechado (só adendo) */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/planos-tratamento': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Planos de tratamento (orçamentos) de um paciente */
    get: {
      parameters: {
        query: {
          paciente_id: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlanoTratamento'][];
          };
        };
      };
    };
    put?: never;
    /** Cria plano de tratamento (orçamento) com itens do catálogo */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            paciente_id: string;
            observacao?: string | null;
            itens: {
              /** Format: uuid */
              catalogo_id: string;
              dente?: number | null;
              faces?: ('V' | 'L' | 'M' | 'D' | 'O' | 'I')[];
              valor?: number | null;
            }[];
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlanoTratamento'];
          };
        };
        /** @description Itens inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/planos-tratamento/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalha o plano */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlanoTratamento'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/planos-tratamento/{id}/aprovar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Aprova o orçamento e lança os itens no prontuário como procedimentos planejados */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PlanoTratamento'];
          };
        };
        /** @description Já aprovado */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/anexos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Anexos do paciente — só metadados (acesso registrado) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Anexo'][];
          };
        };
      };
    };
    put?: never;
    /** Envia anexo (JPG, PNG, WEBP ou PDF até 50 MB) — conteúdo conferido e cifrado no servidor */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'multipart/form-data': {
            /** Format: binary */
            arquivo: string;
            /** @enum {string} */
            tipo: 'radiografia' | 'foto' | 'documento' | 'escaneamento' | 'outro';
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Anexo'];
          };
        };
        /** @description Envio inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Acima de 50 MB */
        413: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Tipo não aceito ou conteúdo diferente do declarado */
        415: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/anexos/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Metadados do anexo + link de uso único (60 s) para visualizar/baixar */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Anexo'] &
              components['schemas']['LinkDownload'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/arquivos/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resgata um link de uso único (anexo ou PDF do prontuário). O token é a credencial. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          token: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Arquivo decifrado (não armazenável em cache) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Link inválido */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/perfis/{perfil}/permissoes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Permissões configuráveis do perfil (hoje, só Laboratório) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          perfil: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PermissoesPerfil'];
          };
        };
        /** @description Perfil inexistente ou de outra unidade */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    /** Substitui as permissões do perfil */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          perfil: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            permissoes: {
              [key: string]: boolean;
            };
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PermissoesPerfil'];
          };
        };
        /** @description Chave desconhecida */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Perfil inexistente ou de outra unidade */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista pacientes (sem termo de busca — use POST /pacientes/buscar) */
    get: {
      parameters: {
        query?: {
          ativo?: 'true' | 'false' | 'todos';
          pagina?: number;
          limite?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              itens: components['schemas']['Paciente'][];
              pagina: number;
              limite: number;
              total: number;
            };
          };
        };
        /** @description Não autenticado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Perfil ou unidade sem permissão */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    /** Cadastra paciente (gera o nº de prontuário) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PacienteEntrada'];
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PacienteFicha'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Somente Secretaria cadastra */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description CPF já cadastrado */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/buscar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Busca pacientes por nome, CPF completo ou parte do celular (termo no corpo, nunca na URL) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            busca: string;
            /** @enum {string} */
            ativo?: 'true' | 'false' | 'todos';
            pagina?: number;
            limite?: number;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              itens: components['schemas']['Paciente'][];
              pagina: number;
              limite: number;
              total: number;
            };
          };
        };
        /** @description Termo ausente ou inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Perfil ou unidade sem permissão */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/exportar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Exporta os pacientes em planilha (CPF e celular mascarados) */
    get: {
      parameters: {
        query: {
          formato: 'xlsx';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Arquivo .xlsx */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Formato não suportado */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Somente Secretaria exporta */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ficha completa do paciente (CPF/celular mascarados; inclui endereço, observações e consentimentos) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PacienteFicha'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Remove o paciente — inativa se houver histórico, exclui se não houver (RN-009) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              acao: 'inativado' | 'excluido';
            };
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Edita o cadastro (mesmos campos do POST, todos opcionais) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PacienteEntrada'];
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PacienteFicha'];
          };
        };
        /** @description Dados inválidos ou ficaria sem CPF e sem responsável */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description CPF já cadastrado */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/pacientes/{id}/resumo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Próximas consultas e OS em aberto (OS entram no M3) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PacienteResumo'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/revelar/{campo}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Revela um campo mascarado (cpf, celular, responsavel_celular) — fica na auditoria */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
          campo: 'cpf' | 'celular' | 'responsavel_celular';
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CampoRevelado'];
          };
        };
        /** @description Campo não revelável */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/pacientes/{id}/consentimento': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Registra consentimento LGPD */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            finalidade: string;
            /** @enum {string} */
            forma: 'presencial' | 'digital' | 'termo_assinado';
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Consentimento'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notificacoes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Notificações do usuário logado (mais recentes primeiro) */
    get: {
      parameters: {
        query?: {
          nao_lidas?: boolean;
          pagina?: number;
          limite?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NotificacoesPagina'];
          };
        };
        /** @description Não autenticado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notificacoes/{id}/lida': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Marca a notificação como lida */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Marcada como lida */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Não encontrada (ou de outro usuário) */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verifica se a API está no ar */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API saudável */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example ok */
              status?: string;
              /** Format: date-time */
              timestamp?: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Autentica e abre a sessão (cookies httpOnly) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            senha: string;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LoginResposta'];
          };
        };
        /** @description Payload inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Credenciais inválidas */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Conta bloqueada temporariamente */
        423: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Limite de requisições excedido */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Renova a sessão (refresh rotativo, via cookie qo_rt) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CsrfResposta'];
          };
        };
        /** @description Refresh inválido */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoga a sessão e limpa os cookies */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sessão encerrada */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Não autenticado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Token CSRF ausente ou inválido (header X-CSRF-Token) */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Usuário logado e suas permissões */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Me'];
          };
        };
        /** @description Não autenticado */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/esqueci-senha': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Envia link de redefinição (resposta igual exista ou não o e-mail) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Solicitação aceita */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Payload inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Limite de requisições excedido */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/redefinir-senha': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Redefine a senha com o token recebido por e-mail (uso único) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            token: string;
            novaSenha: string;
          };
        };
      };
      responses: {
        /** @description Senha redefinida; sessões anteriores revogadas */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Token inválido/expirado ou senha fora da política */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Limite de requisições excedido */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auditoria': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Trilha de auditoria da unidade (filtrável por entidade, usuário e período) */
    get: {
      parameters: {
        query?: {
          entidade?: string;
          entidade_id?: string;
          usuario?: string;
          inicio?: string;
          fim?: string;
          pagina?: number;
          limite?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              itens: components['schemas']['AuditoriaItem'][];
              pagina: number;
              limite: number;
              total: number;
            };
          };
        };
        /** @description Filtro inválido */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Perfil sem permissão */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profissionais': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lista profissionais (Secretaria, Clínica e Adm. Clínica leem) */
    get: {
      parameters: {
        query?: {
          /** @description true inclui inativos (só Adm. Clínica) */
          todos?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Profissional'][];
          };
        };
        /** @description Sem permissão */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    /** Cadastra profissional a partir de um usuário com perfil Clínica */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            usuario_id: string;
            cro: string;
            especialidade?: string | null;
            cor_agenda?: string | null;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Profissional'];
          };
        };
        /** @description Dados inválidos ou usuário sem perfil Clínica */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Somente Adm. Clínica */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Usuário já é profissional */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/profissionais/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Edita CRO, especialidade, cor ou ativa/inativa */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            cro?: string;
            especialidade?: string | null;
            cor_agenda?: string;
            ativo?: boolean;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Profissional'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/profissionais/{id}/horarios': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Jornada semanal do profissional */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Horarios'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    /** Substitui a jornada semanal */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['Horarios'];
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Horarios'];
          };
        };
        /** @description Janelas inválidas ou sobrepostas */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/consultas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consultas de um período (dia, semana, mês ou quadro) */
    get: {
      parameters: {
        query: {
          inicio: string;
          fim: string;
          profissional?: string;
          status?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Consulta'][];
          };
        };
        /** @description Filtros inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Sem permissão */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    /** Agenda consulta (RN-002 — sem conflito de profissional/cadeira; respeita jornada e bloqueios) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            paciente_id: string;
            /** Format: uuid */
            profissional_id: string;
            cadeira?: number;
            /** Format: date-time */
            inicio: string;
            /** Format: date-time */
            fim: string;
            procedimento_previsto?: string | null;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Consulta'];
          };
        };
        /** @description Dados inválidos ou paciente inativo */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Somente Secretaria agenda */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Conflito de horário */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/consultas/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalha a consulta com o histórico de status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Consulta'];
          };
        };
        /** @description Não encontrada */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Reagenda (profissional, cadeira, horário, procedimento) — só consultas agendada/confirmada */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            profissional_id?: string;
            cadeira?: number;
            /** Format: date-time */
            inicio?: string;
            /** Format: date-time */
            fim?: string;
            procedimento_previsto?: string | null;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Consulta'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Não encontrada */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Conflito de horário ou status não permite */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/consultas/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Move no quadro (agendada → confirmada → chegou → em_atendimento → concluida; faltou) e grava histórico */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** @enum {string} */
            status: 'confirmada' | 'chegou' | 'em_atendimento' | 'concluida' | 'faltou';
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Consulta'];
          };
        };
        /** @description Status inválido (cancelamento usa /cancelar) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Transição não permitida */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    trace?: never;
  };
  '/consultas/{id}/cancelar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancela com motivo e libera o horário (RN-010) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            motivo: string;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Consulta'];
          };
        };
        /** @description Motivo ausente */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Status não permite cancelar */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/consultas/{id}/lembrete-whatsapp': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Link wa.me com a mensagem de lembrete pronta (registrado na auditoria) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Lembrete'];
          };
        };
        /** @description Paciente sem celular */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Consulta não está a realizar */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bloqueios-agenda': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bloqueios de um período (inclui os da clínica toda) */
    get: {
      parameters: {
        query: {
          inicio: string;
          fim: string;
          profissional?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Bloqueio'][];
          };
        };
        /** @description Filtros inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Sem permissão */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    /** Cria bloqueio (profissional_id nulo = clínica toda); recusa se houver consultas no período */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            profissional_id?: string | null;
            /** Format: date-time */
            inicio: string;
            /** Format: date-time */
            fim: string;
            motivo: string;
          };
        };
      };
      responses: {
        /** @description Sucesso */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Bloqueio'];
          };
        };
        /** @description Dados inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Há consultas no período */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bloqueios-agenda/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove o bloqueio */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Removido */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/agenda/disponibilidade': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Horários livres do profissional num dia (jornada menos consultas ativas e bloqueios) */
    get: {
      parameters: {
        query: {
          profissional: string;
          data: string;
          duracao?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Sucesso */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Disponibilidade'];
          };
        };
        /** @description Filtros inválidos */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
        /** @description Profissional não encontrado */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Erro'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Alerta: {
      /** @enum {string} */
      tipo: 'alergia' | 'medicamento' | 'condicao' | 'outro';
      descricao: string;
    };
    AnamneseMeta: {
      /** Format: uuid */
      id: string;
      versao: number;
      /** Format: date-time */
      assinada_em?: string | null;
      /** Format: date-time */
      criado_em: string;
      profissional_nome: string;
    };
    Anamnese: components['schemas']['AnamneseMeta'] & {
      /** Format: uuid */
      paciente_id: string;
      respostas: {
        [key: string]: unknown;
      };
      alertas: components['schemas']['Alerta'][];
    };
    Adendo: {
      /** Format: uuid */
      id: string;
      conteudo: string;
      /** Format: date-time */
      criado_em: string;
      profissional_nome?: string;
    };
    Evolucao: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      consulta_id?: string | null;
      conteudo: string;
      /** Format: date-time */
      criado_em: string;
      profissional_nome: string;
      adendos: components['schemas']['Adendo'][];
    };
    ItemLinhaTempo: {
      /** @enum {string} */
      tipo: 'evolucao' | 'anamnese' | 'procedimento' | 'anexo' | 'consulta';
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      em: string;
      autor?: string | null;
      titulo: string;
      resumo?: string | null;
    };
    Prontuario: {
      paciente: {
        /** Format: uuid */
        id: string;
        nome: string;
        numero_prontuario: number;
        /** Format: date */
        nascimento?: string | null;
        sexo?: string | null;
        ativo: boolean;
      };
      anamnese_atual?: components['schemas']['AnamneseMeta'] | null;
      alertas: components['schemas']['Alerta'][];
      linha_do_tempo: components['schemas']['ItemLinhaTempo'][];
    };
    Acesso: {
      /** Format: date-time */
      em: string;
      recurso: string;
      usuario_nome?: string | null;
      usuario_perfil?: string | null;
    };
    ItemCatalogo: {
      /** Format: uuid */
      id: string;
      codigo: string;
      nome: string;
      especialidade?: string | null;
      duracao_min: number;
      valor_padrao: number;
      ativo: boolean;
    };
    ProcedimentoPaciente: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      paciente_id: string;
      catalogo: {
        /** Format: uuid */
        id: string;
        codigo: string;
        nome: string;
      };
      dente?: number | null;
      faces: ('V' | 'L' | 'M' | 'D' | 'O' | 'I')[];
      /** @enum {string} */
      status: 'planejado' | 'em_andamento' | 'concluido' | 'cancelado';
      /** Format: date */
      data?: string | null;
      valor: number;
      observacao?: string | null;
      profissional_nome?: string | null;
      /** Format: uuid */
      plano_id?: string | null;
      /** Format: date-time */
      criado_em: string;
      adendos: {
        /** Format: uuid */
        id: string;
        conteudo: string;
        /** Format: date-time */
        criado_em: string;
        autor?: string | null;
      }[];
    };
    Odontograma: {
      dentes: {
        [key: string]: {
          /** @enum {string|null} */
          situacao: 'planejado' | 'em_andamento' | 'concluido' | null;
          procedimentos: {
            /** Format: uuid */
            id: string;
            nome: string;
            faces: string[];
            /** @enum {string} */
            status: 'planejado' | 'em_andamento' | 'concluido' | 'cancelado';
            /** Format: date */
            data?: string | null;
          }[];
        };
      };
    };
    PlanoTratamento: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      paciente_id: string;
      /** @enum {string} */
      status: 'rascunho' | 'aprovado';
      observacao?: string | null;
      total: number;
      profissional_nome?: string | null;
      criado_por_nome?: string | null;
      /** Format: date-time */
      criado_em: string;
      /** Format: date-time */
      aprovado_em?: string | null;
      aprovado_por_nome?: string | null;
      itens: {
        /** Format: uuid */
        id: string;
        catalogo: {
          /** Format: uuid */
          id: string;
          codigo: string;
          nome: string;
        };
        dente?: number | null;
        faces: string[];
        valor: number;
        /** Format: uuid */
        procedimento_id?: string | null;
      }[];
    };
    Anexo: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      paciente_id?: string | null;
      /** @enum {string} */
      tipo: 'radiografia' | 'foto' | 'documento' | 'escaneamento' | 'outro';
      nome: string;
      mime: string;
      tamanho: number;
      /** Format: date-time */
      criado_em: string;
      enviado_por?: string | null;
    };
    LinkDownload: {
      url: string;
      /** Format: date-time */
      expira_em: string;
    };
    Erro: {
      erro: string;
    };
    UsuarioSessao: {
      /** Format: uuid */
      id: string;
      nome: string;
      /** @enum {string} */
      perfil: 'secretaria' | 'clinica' | 'adm_clinica' | 'laboratorio' | 'adm_laboratorio';
      /** @enum {string} */
      unidade: 'clinica' | 'laboratorio';
    };
    LoginResposta: {
      usuario: components['schemas']['UsuarioSessao'];
      csrfToken: string;
    };
    CsrfResposta: {
      csrfToken: string;
    };
    Me: {
      /** Format: uuid */
      id: string;
      nome: string;
      /** @enum {string} */
      perfil: 'secretaria' | 'clinica' | 'adm_clinica' | 'laboratorio' | 'adm_laboratorio';
      /** @enum {string} */
      unidade: 'clinica' | 'laboratorio';
      permissoes: {
        [key: string]: boolean;
      };
      csrfToken: string;
    };
    Usuario: {
      /** Format: uuid */
      id: string;
      nome: string;
      email: string;
      /** @enum {string} */
      perfil: 'secretaria' | 'clinica' | 'adm_clinica' | 'laboratorio' | 'adm_laboratorio';
      /** @enum {string} */
      unidade: 'clinica' | 'laboratorio';
      /** @enum {string} */
      status: 'ativo' | 'bloqueado' | 'convidado';
      /** Format: date-time */
      ultimo_acesso?: string | null;
      /** Format: date-time */
      criado_em: string;
    };
    PermissoesPerfil: {
      perfil: string;
      permissoes: {
        [key: string]: boolean;
      };
    };
    AuditoriaItem: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      em: string;
      entidade: string;
      entidade_id?: string | null;
      acao: string;
      antes?: {
        [key: string]: unknown;
      } | null;
      depois?: {
        [key: string]: unknown;
      } | null;
      ip?: string | null;
      usuario_nome?: string | null;
    };
    Notificacao: {
      /** Format: uuid */
      id: string;
      tipo: string;
      titulo: string;
      link?: string | null;
      /** Format: date-time */
      lida_em?: string | null;
      /** Format: date-time */
      criado_em: string;
    };
    NotificacoesPagina: {
      itens: components['schemas']['Notificacao'][];
      pagina: number;
      limite: number;
      nao_lidas: number;
    };
    Endereco: {
      cep?: string;
      logradouro?: string;
      numero?: string;
      complemento?: string;
      bairro?: string;
      cidade?: string;
      uf?: string;
    };
    Responsavel: {
      nome: string;
      parentesco?: string | null;
      celular?: string | null;
    };
    Paciente: {
      /** Format: uuid */
      id: string;
      numero_prontuario: number;
      nome: string;
      /** @description Sempre mascarado */
      cpf?: string | null;
      /** Format: date */
      nascimento?: string | null;
      /** @enum {string|null} */
      sexo?: 'F' | 'M' | 'O' | null;
      /** @description Sempre mascarado */
      celular?: string | null;
      email?: string | null;
      responsavel?: components['schemas']['Responsavel'] | null;
      origem?: string | null;
      ativo: boolean;
      /** Format: date-time */
      criado_em: string;
    };
    Consentimento: {
      /** Format: uuid */
      id: string;
      finalidade: string;
      /** @enum {string} */
      forma: 'presencial' | 'digital' | 'termo_assinado';
      /** Format: date-time */
      data: string;
    };
    PacienteFicha: components['schemas']['Paciente'] & {
      endereco?: components['schemas']['Endereco'] | null;
      observacoes?: string | null;
      consentimentos?: components['schemas']['Consentimento'][];
    };
    PacienteEntrada: {
      nome: string;
      cpf?: string | null;
      /** Format: date */
      nascimento?: string | null;
      /** @enum {string|null} */
      sexo?: 'F' | 'M' | 'O' | null;
      celular?: string | null;
      email?: string | null;
      endereco?: components['schemas']['Endereco'] | null;
      responsavel_nome?: string | null;
      responsavel_parentesco?: string | null;
      responsavel_celular?: string | null;
      origem?: string | null;
      observacoes?: string | null;
    };
    ConsultaProxima: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      inicio: string;
      /** Format: date-time */
      fim: string;
      /** @enum {string} */
      status:
        | 'agendada'
        | 'confirmada'
        | 'chegou'
        | 'em_atendimento'
        | 'concluida'
        | 'faltou'
        | 'cancelada';
      procedimento_previsto?: string | null;
      profissional_nome?: string;
    };
    PacienteResumo: {
      paciente: components['schemas']['Paciente'];
      proximas_consultas: components['schemas']['ConsultaProxima'][];
      os_em_aberto: {
        [key: string]: unknown;
      }[];
    };
    CampoRevelado: {
      campo: string;
      valor: string | null;
    };
    Profissional: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      usuario_id: string;
      nome: string;
      cro: string;
      especialidade?: string | null;
      cor_agenda: string;
      ativo: boolean;
    };
    Horario: {
      dia_semana: number;
      inicio: string;
      fim: string;
    };
    Horarios: {
      horarios: components['schemas']['Horario'][];
    };
    HistoricoConsulta: {
      de_status?: string | null;
      /** @enum {string} */
      para_status:
        | 'agendada'
        | 'confirmada'
        | 'chegou'
        | 'em_atendimento'
        | 'concluida'
        | 'faltou'
        | 'cancelada';
      observacao?: string | null;
      /** Format: date-time */
      em: string;
      usuario_nome?: string | null;
    };
    Consulta: {
      /** Format: uuid */
      id: string;
      /** Format: date-time */
      inicio: string;
      /** Format: date-time */
      fim: string;
      cadeira: number;
      /** @enum {string} */
      status:
        | 'agendada'
        | 'confirmada'
        | 'chegou'
        | 'em_atendimento'
        | 'concluida'
        | 'faltou'
        | 'cancelada';
      procedimento_previsto?: string | null;
      motivo_cancelamento?: string | null;
      paciente: {
        /** Format: uuid */
        id: string;
        nome: string;
      };
      profissional: {
        /** Format: uuid */
        id: string;
        nome: string;
        cor_agenda: string;
      };
      historico?: components['schemas']['HistoricoConsulta'][];
    };
    Bloqueio: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      profissional_id?: string | null;
      profissional_nome?: string | null;
      /** Format: date-time */
      inicio: string;
      /** Format: date-time */
      fim: string;
      motivo: string;
    };
    Disponibilidade: {
      /** Format: uuid */
      profissional: string;
      data: string;
      duracao: number;
      livres: {
        /** Format: date-time */
        inicio: string;
        /** Format: date-time */
        fim: string;
      }[];
    };
    Lembrete: {
      url: string;
      /** @description Mascarado */
      celular: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
